name: 'K8S Internals'

#on:
#  workflow_run:
#    workflows: ['Terraform TST', 'Terraform ACC', 'Terraform PRD']
#    types: [completed]

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  k8s-internals:
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Fetch AKS kubeconfig
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            {
            echo 'KUBE_CONFIG<<EOF'
            az aks get-credentials --resource-group rg-cicd-apps --name cicdcluster --file -
            echo EOF
            } >> "$GITHUB_ENV" 
            

#            echo "KUBE_CONFIG=`az aks get-credentials --resource-group rg-cicd-apps --name cicdcluster --file -`" >> $GITHUB_ENV

#      - name: Fetch AKS kubeconfig
#        run: echo "KUBE_CONFIG=`az aks get-credentials --resource-group rg-cicd-apps --name cicdcluster --file -`" >> $GITHUB_ENV

      - name: Add kubeconfig to repo secrets
        uses: action-pack/set-secret@v1
        with:
          name: 'KUBE_CONFIG'
          value: ${{ env.KUBE_CONFIG }}
          token: ${{ secrets.REGISTRY_TOKEN }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4.0.0

      - name: Create pull secret
        run: |
          kubectl create secret docker-registry registrypullsecret --docker-username=corbencreatives --docker-password=${{ secrets.DOCKER_PASSWORD }} --docker-server=https://ghcr.io -n cicd          
