name: 'Security'

on:
  pull_request:
    types: [opened, reopened]
  merge_group:
    branches: [develop, main]

jobs:
  call-terraform-security:
    if: github.event_name == 'pull_request' # only run job if workflow initiated by a pull request event
    uses: corbencreatives/action-workflows/.github/workflows/terraform-security.yml@v0.5.2
    with:
      terraform-path: "./terraform"
    permissions:
      contents: read
      security-events: write
