name: 'Terraform TST'

on:
  pull_request:
    types: [closed]
    branches: [develop]
    paths:
      - 'terraform/**'
      - '.github/workflows/**'

env:
  REGISTRY: ghcr.io

jobs:
  checkout-and-login:
    name: "Checkout code and login to Azure"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

  call-terraform-plan-apply:
    name: "Call the reusable terraform plan and apply action"
    needs: checkout-and-login
    #    if: github.event_name == 'pull_request' # only run job if workflow initiated by a pull request event
    permissions:
      contents: read
      pull-requests: write
    uses: corbencreatives/action-workflows/.github/workflows/terraform-plan-apply.yml@v0.5.34
    with:
      environment: "test"
      tf-workspace: "actions-infra"
      config-directory: "./terraform"
    secrets: inherit
#    secrets:
#      token: ${{secrets.TF_API_TOKEN}}
##      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID_QUOTED}}
##      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET_QUOTED }}
##      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID_QUOTED }}
##      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID_QUOTED }}
#      DOCKER_PASSWORD: ${{ secrets.REGISTRY_TOKEN_QUOTED }}


