name: 'Terraform TST'

on:
  pull_request:
    types: [closed]
    branches: [develop]
    paths:
      - 'terraform/**'
      - '.github/workflows/**'

jobs:
  call-terraform-plan-apply:
    name: "Call the reusable terraform plan and apply action"
    #    if: github.event_name == 'pull_request' # only run job if workflow initiated by a pull request event
    permissions:
      contents: read
      pull-requests: write
    uses: corbencreatives/action-workflows/.github/workflows/terraform-plan-apply.yml@develop
    with:
      environment: "test"
      tf-workspace: "actions-infra"
      config-directory: "./terraform"
    secrets: inherit
